### ISSUE TITLE
Mutex necessary?

### ISSUE THREAD

**Issue by trevex** [haw-mip02/data-acquisition#1]
I am no python expert and this is definitely premature optimization, but as far as I can see the only possible unsafe operation is copying and clearing the list, because the size of the list can change in-between. This can be avoided however if the list is sliced and only partially deleted, e.g.

```
l = len(tweets)
tweets_copy = tweets[:l]
del tweets[:l]
```

Then all operations are threadsafe and the mutex can be avoided, since the GIL is locking access anyway.

**Comment by BirgerK** [comment]
Hi trevex,

cause our project is documented in german (and the group is communicating in german) I'll answer in german:

Ja, es kann sein, dass Python-Listen ein threadsafe `append()` haben. Allerdings wollten wir dort nicht in irgendwelche Edge-Cases reinlaufen, daher haben wir unseren eigenen Mutex dafür konstruiert.

Ja, es kann sein, dass zwischen dem Aufruf `ThreadSafeList.append()` und `ThreadSafeList.flush_and_return_all()` sich die Größe der Liste verändert. Allerdings ist dieser Größenunterschied nicht relevant. Ob wir nun 10 oder 30 Elemente an die REST-API übergeben, sollte keinen Unterschied machen.

Wie gesagt: Wir wollten uns nicht auf einige wenige threadsafe-Operationen der Python-Liste verlassen. Es gibt einige Operationen, die sind threadsafe und es gibt welche, die sind es nicht. So haben wir eine einheitliche Lösung für unsere `ThreadSafeList`. :)

**Comment by trevex** [comment]
Wie gesagt war nur 

> premature optimization

:P
